using System.Collections.Generic;

namespace TestProject1.ForTest
{
    public class Const
    {
        public static readonly List<KanaTrio> SEION_LIST = new List<KanaTrio>(new[]
        {
            new KanaTrio() {Hiragana = "ぁ", KatakanaZen = "ァ", KatakanaHan = "ｧ"},
            new KanaTrio() {Hiragana = "あ", KatakanaZen = "ア", KatakanaHan = "ｱ"},
            new KanaTrio() {Hiragana = "ぃ", KatakanaZen = "ィ", KatakanaHan = "ｨ"},
            new KanaTrio() {Hiragana = "い", KatakanaZen = "イ", KatakanaHan = "ｲ"},
            new KanaTrio() {Hiragana = "ぅ", KatakanaZen = "ゥ", KatakanaHan = "ｩ"},
            new KanaTrio() {Hiragana = "う", KatakanaZen = "ウ", KatakanaHan = "ｳ"},
            new KanaTrio() {Hiragana = "ぇ", KatakanaZen = "ェ", KatakanaHan = "ｪ"},
            new KanaTrio() {Hiragana = "え", KatakanaZen = "エ", KatakanaHan = "ｴ"},
            new KanaTrio() {Hiragana = "ぉ", KatakanaZen = "ォ", KatakanaHan = "ｫ"},
            new KanaTrio() {Hiragana = "お", KatakanaZen = "オ", KatakanaHan = "ｵ"},
            new KanaTrio() {Hiragana = "か", KatakanaZen = "カ", KatakanaHan = "ｶ"},
            new KanaTrio() {Hiragana = "き", KatakanaZen = "キ", KatakanaHan = "ｷ"},
            new KanaTrio() {Hiragana = "く", KatakanaZen = "ク", KatakanaHan = "ｸ"},
            new KanaTrio() {Hiragana = "け", KatakanaZen = "ケ", KatakanaHan = "ｹ"},
            new KanaTrio() {Hiragana = "こ", KatakanaZen = "コ", KatakanaHan = "ｺ"},
            new KanaTrio() {Hiragana = "さ", KatakanaZen = "サ", KatakanaHan = "ｻ"},
            new KanaTrio() {Hiragana = "し", KatakanaZen = "シ", KatakanaHan = "ｼ"},
            new KanaTrio() {Hiragana = "す", KatakanaZen = "ス", KatakanaHan = "ｽ"},
            new KanaTrio() {Hiragana = "せ", KatakanaZen = "セ", KatakanaHan = "ｾ"},
            new KanaTrio() {Hiragana = "そ", KatakanaZen = "ソ", KatakanaHan = "ｿ"},
            new KanaTrio() {Hiragana = "た", KatakanaZen = "タ", KatakanaHan = "ﾀ"},
            new KanaTrio() {Hiragana = "ち", KatakanaZen = "チ", KatakanaHan = "ﾁ"},
            new KanaTrio() {Hiragana = "っ", KatakanaZen = "ッ", KatakanaHan = "ｯ"},
            new KanaTrio() {Hiragana = "つ", KatakanaZen = "ツ", KatakanaHan = "ﾂ"},
            new KanaTrio() {Hiragana = "て", KatakanaZen = "テ", KatakanaHan = "ﾃ"},
            new KanaTrio() {Hiragana = "と", KatakanaZen = "ト", KatakanaHan = "ﾄ"},
            new KanaTrio() {Hiragana = "な", KatakanaZen = "ナ", KatakanaHan = "ﾅ"},
            new KanaTrio() {Hiragana = "に", KatakanaZen = "ニ", KatakanaHan = "ﾆ"},
            new KanaTrio() {Hiragana = "ぬ", KatakanaZen = "ヌ", KatakanaHan = "ﾇ"},
            new KanaTrio() {Hiragana = "ね", KatakanaZen = "ネ", KatakanaHan = "ﾈ"},
            new KanaTrio() {Hiragana = "の", KatakanaZen = "ノ", KatakanaHan = "ﾉ"},
            new KanaTrio() {Hiragana = "は", KatakanaZen = "ハ", KatakanaHan = "ﾊ"},
            new KanaTrio() {Hiragana = "ひ", KatakanaZen = "ヒ", KatakanaHan = "ﾋ"},
            new KanaTrio() {Hiragana = "ふ", KatakanaZen = "フ", KatakanaHan = "ﾌ"},
            new KanaTrio() {Hiragana = "へ", KatakanaZen = "ヘ", KatakanaHan = "ﾍ"},
            new KanaTrio() {Hiragana = "ほ", KatakanaZen = "ホ", KatakanaHan = "ﾎ"},
            new KanaTrio() {Hiragana = "ま", KatakanaZen = "マ", KatakanaHan = "ﾏ"},
            new KanaTrio() {Hiragana = "み", KatakanaZen = "ミ", KatakanaHan = "ﾐ"},
            new KanaTrio() {Hiragana = "む", KatakanaZen = "ム", KatakanaHan = "ﾑ"},
            new KanaTrio() {Hiragana = "め", KatakanaZen = "メ", KatakanaHan = "ﾒ"},
            new KanaTrio() {Hiragana = "も", KatakanaZen = "モ", KatakanaHan = "ﾓ"},
            new KanaTrio() {Hiragana = "ゃ", KatakanaZen = "ャ", KatakanaHan = "ｬ"},
            new KanaTrio() {Hiragana = "や", KatakanaZen = "ヤ", KatakanaHan = "ﾔ"},
            new KanaTrio() {Hiragana = "ゅ", KatakanaZen = "ュ", KatakanaHan = "ｭ"},
            new KanaTrio() {Hiragana = "ゆ", KatakanaZen = "ユ", KatakanaHan = "ﾕ"},
            new KanaTrio() {Hiragana = "ょ", KatakanaZen = "ョ", KatakanaHan = "ｮ"},
            new KanaTrio() {Hiragana = "よ", KatakanaZen = "ヨ", KatakanaHan = "ﾖ"},
            new KanaTrio() {Hiragana = "ら", KatakanaZen = "ラ", KatakanaHan = "ﾗ"},
            new KanaTrio() {Hiragana = "り", KatakanaZen = "リ", KatakanaHan = "ﾘ"},
            new KanaTrio() {Hiragana = "る", KatakanaZen = "ル", KatakanaHan = "ﾙ"},
            new KanaTrio() {Hiragana = "れ", KatakanaZen = "レ", KatakanaHan = "ﾚ"},
            new KanaTrio() {Hiragana = "ろ", KatakanaZen = "ロ", KatakanaHan = "ﾛ"},
            new KanaTrio() {Hiragana = "ゎ", KatakanaZen = "ヮ", KatakanaHan = "ヮ"},
            new KanaTrio() {Hiragana = "わ", KatakanaZen = "ワ", KatakanaHan = "ﾜ"},
            new KanaTrio() {Hiragana = "ゐ", KatakanaZen = "ヰ", KatakanaHan = "ヰ"},
            new KanaTrio() {Hiragana = "ゑ", KatakanaZen = "ヱ", KatakanaHan = "ヱ"},
            new KanaTrio() {Hiragana = "を", KatakanaZen = "ヲ", KatakanaHan = "ｦ"},
            new KanaTrio() {Hiragana = "ん", KatakanaZen = "ン", KatakanaHan = "ﾝ"}
        });

        public static readonly List<KanaTrio> DAKUON_LIST = new List<KanaTrio>(new[]
        {
            new KanaTrio() {Hiragana = "が", KatakanaZen = "ガ", KatakanaHan = "ｶﾞ"},
            new KanaTrio() {Hiragana = "ぎ", KatakanaZen = "ギ", KatakanaHan = "ｷﾞ"},
            new KanaTrio() {Hiragana = "ぐ", KatakanaZen = "グ", KatakanaHan = "ｸﾞ"},
            new KanaTrio() {Hiragana = "げ", KatakanaZen = "ゲ", KatakanaHan = "ｹﾞ"},
            new KanaTrio() {Hiragana = "ご", KatakanaZen = "ゴ", KatakanaHan = "ｺﾞ"},
            new KanaTrio() {Hiragana = "ざ", KatakanaZen = "ザ", KatakanaHan = "ｻﾞ"},
            new KanaTrio() {Hiragana = "じ", KatakanaZen = "ジ", KatakanaHan = "ｼﾞ"},
            new KanaTrio() {Hiragana = "ず", KatakanaZen = "ズ", KatakanaHan = "ｽﾞ"},
            new KanaTrio() {Hiragana = "ぜ", KatakanaZen = "ゼ", KatakanaHan = "ｾﾞ"},
            new KanaTrio() {Hiragana = "ぞ", KatakanaZen = "ゾ", KatakanaHan = "ｿﾞ"},
            new KanaTrio() {Hiragana = "だ", KatakanaZen = "ダ", KatakanaHan = "ﾀﾞ"},
            new KanaTrio() {Hiragana = "ぢ", KatakanaZen = "ヂ", KatakanaHan = "ﾁﾞ"},
            new KanaTrio() {Hiragana = "づ", KatakanaZen = "ヅ", KatakanaHan = "ﾂﾞ"},
            new KanaTrio() {Hiragana = "で", KatakanaZen = "デ", KatakanaHan = "ﾃﾞ"},
            new KanaTrio() {Hiragana = "ど", KatakanaZen = "ド", KatakanaHan = "ﾄﾞ"},
            new KanaTrio() {Hiragana = "ば", KatakanaZen = "バ", KatakanaHan = "ﾊﾞ"},
            new KanaTrio() {Hiragana = "ぱ", KatakanaZen = "パ", KatakanaHan = "ﾊﾟ"},
            new KanaTrio() {Hiragana = "び", KatakanaZen = "ビ", KatakanaHan = "ﾋﾞ"},
            new KanaTrio() {Hiragana = "ぴ", KatakanaZen = "ピ", KatakanaHan = "ﾋﾟ"},
            new KanaTrio() {Hiragana = "ぶ", KatakanaZen = "ブ", KatakanaHan = "ﾌﾞ"},
            new KanaTrio() {Hiragana = "ぷ", KatakanaZen = "プ", KatakanaHan = "ﾌﾟ"},
            new KanaTrio() {Hiragana = "べ", KatakanaZen = "ベ", KatakanaHan = "ﾍﾞ"},
            new KanaTrio() {Hiragana = "ぺ", KatakanaZen = "ペ", KatakanaHan = "ﾍﾟ"},
            new KanaTrio() {Hiragana = "ぼ", KatakanaZen = "ボ", KatakanaHan = "ﾎﾞ"},
            new KanaTrio() {Hiragana = "ぽ", KatakanaZen = "ポ", KatakanaHan = "ﾎﾟ"},
            new KanaTrio() {Hiragana = "ゔ", KatakanaZen = "ヴ", KatakanaHan = "ｳﾞ"}
        });

        public static readonly List<NarrowWidePair> ZEN_HAN_LIST = new List<NarrowWidePair>(new[]
        {
            new NarrowWidePair() {Hankaku = "A", Zenkaku = "Ａ"},
            new NarrowWidePair() {Hankaku = "B", Zenkaku = "Ｂ"},
            new NarrowWidePair() {Hankaku = "C", Zenkaku = "Ｃ"},
            new NarrowWidePair() {Hankaku = "D", Zenkaku = "Ｄ"},
            new NarrowWidePair() {Hankaku = "E", Zenkaku = "Ｅ"},
            new NarrowWidePair() {Hankaku = "F", Zenkaku = "Ｆ"},
            new NarrowWidePair() {Hankaku = "G", Zenkaku = "Ｇ"},
            new NarrowWidePair() {Hankaku = "H", Zenkaku = "Ｈ"},
            new NarrowWidePair() {Hankaku = "I", Zenkaku = "Ｉ"},
            new NarrowWidePair() {Hankaku = "J", Zenkaku = "Ｊ"},
            new NarrowWidePair() {Hankaku = "K", Zenkaku = "Ｋ"},
            new NarrowWidePair() {Hankaku = "L", Zenkaku = "Ｌ"},
            new NarrowWidePair() {Hankaku = "M", Zenkaku = "Ｍ"},
            new NarrowWidePair() {Hankaku = "N", Zenkaku = "Ｎ"},
            new NarrowWidePair() {Hankaku = "O", Zenkaku = "Ｏ"},
            new NarrowWidePair() {Hankaku = "P", Zenkaku = "Ｐ"},
            new NarrowWidePair() {Hankaku = "Q", Zenkaku = "Ｑ"},
            new NarrowWidePair() {Hankaku = "R", Zenkaku = "Ｒ"},
            new NarrowWidePair() {Hankaku = "S", Zenkaku = "Ｓ"},
            new NarrowWidePair() {Hankaku = "T", Zenkaku = "Ｔ"},
            new NarrowWidePair() {Hankaku = "U", Zenkaku = "Ｕ"},
            new NarrowWidePair() {Hankaku = "V", Zenkaku = "Ｖ"},
            new NarrowWidePair() {Hankaku = "W", Zenkaku = "Ｗ"},
            new NarrowWidePair() {Hankaku = "X", Zenkaku = "Ｘ"},
            new NarrowWidePair() {Hankaku = "Y", Zenkaku = "Ｙ"},
            new NarrowWidePair() {Hankaku = "Z", Zenkaku = "Ｚ"},
            new NarrowWidePair() {Hankaku = "a", Zenkaku = "ａ"},
            new NarrowWidePair() {Hankaku = "b", Zenkaku = "ｂ"},
            new NarrowWidePair() {Hankaku = "c", Zenkaku = "ｃ"},
            new NarrowWidePair() {Hankaku = "d", Zenkaku = "ｄ"},
            new NarrowWidePair() {Hankaku = "e", Zenkaku = "ｅ"},
            new NarrowWidePair() {Hankaku = "f", Zenkaku = "ｆ"},
            new NarrowWidePair() {Hankaku = "g", Zenkaku = "ｇ"},
            new NarrowWidePair() {Hankaku = "h", Zenkaku = "ｈ"},
            new NarrowWidePair() {Hankaku = "i", Zenkaku = "ｉ"},
            new NarrowWidePair() {Hankaku = "j", Zenkaku = "ｊ"},
            new NarrowWidePair() {Hankaku = "k", Zenkaku = "ｋ"},
            new NarrowWidePair() {Hankaku = "l", Zenkaku = "ｌ"},
            new NarrowWidePair() {Hankaku = "m", Zenkaku = "ｍ"},
            new NarrowWidePair() {Hankaku = "n", Zenkaku = "ｎ"},
            new NarrowWidePair() {Hankaku = "o", Zenkaku = "ｏ"},
            new NarrowWidePair() {Hankaku = "p", Zenkaku = "ｐ"},
            new NarrowWidePair() {Hankaku = "q", Zenkaku = "ｑ"},
            new NarrowWidePair() {Hankaku = "r", Zenkaku = "ｒ"},
            new NarrowWidePair() {Hankaku = "s", Zenkaku = "ｓ"},
            new NarrowWidePair() {Hankaku = "t", Zenkaku = "ｔ"},
            new NarrowWidePair() {Hankaku = "u", Zenkaku = "ｕ"},
            new NarrowWidePair() {Hankaku = "v", Zenkaku = "ｖ"},
            new NarrowWidePair() {Hankaku = "w", Zenkaku = "ｗ"},
            new NarrowWidePair() {Hankaku = "x", Zenkaku = "ｘ"},
            new NarrowWidePair() {Hankaku = "y", Zenkaku = "ｙ"},
            new NarrowWidePair() {Hankaku = "z", Zenkaku = "ｚ"},
            new NarrowWidePair() {Hankaku = "0", Zenkaku = "０"},
            new NarrowWidePair() {Hankaku = "1", Zenkaku = "１"},
            new NarrowWidePair() {Hankaku = "2", Zenkaku = "２"},
            new NarrowWidePair() {Hankaku = "3", Zenkaku = "３"},
            new NarrowWidePair() {Hankaku = "4", Zenkaku = "４"},
            new NarrowWidePair() {Hankaku = "5", Zenkaku = "５"},
            new NarrowWidePair() {Hankaku = "6", Zenkaku = "６"},
            new NarrowWidePair() {Hankaku = "7", Zenkaku = "７"},
            new NarrowWidePair() {Hankaku = "8", Zenkaku = "８"},
            new NarrowWidePair() {Hankaku = "9", Zenkaku = "９"},
            
            new NarrowWidePair() {Hankaku = "･", Zenkaku = "・"},
            new NarrowWidePair() {Hankaku = "/", Zenkaku = "／"},

            new NarrowWidePair() {Hankaku = "@", Zenkaku = "＠"},
            new NarrowWidePair() {Hankaku = ".", Zenkaku = "．"},
            new NarrowWidePair() {Hankaku = "_", Zenkaku = "＿"},
            new NarrowWidePair() {Hankaku = "ｰ", Zenkaku = "ー"},
            new NarrowWidePair() {Hankaku = ",", Zenkaku = "，"},
            new NarrowWidePair() {Hankaku = "?", Zenkaku = "？"},
            new NarrowWidePair() {Hankaku = "&", Zenkaku = "＆"},
            new NarrowWidePair() {Hankaku = "%", Zenkaku = "％"},
            new NarrowWidePair() {Hankaku = "!", Zenkaku = "！"},
            new NarrowWidePair() {Hankaku = "\"", Zenkaku = "”"},
            new NarrowWidePair() {Hankaku = "'", Zenkaku = "’"},
            new NarrowWidePair() {Hankaku = "(", Zenkaku = "（"},
            new NarrowWidePair() {Hankaku = ")", Zenkaku = "）"},
            new NarrowWidePair() {Hankaku = "#", Zenkaku = "＃"},
            new NarrowWidePair() {Hankaku = "｢", Zenkaku = "「"},
            new NarrowWidePair() {Hankaku = "｣", Zenkaku = "」"},
            new NarrowWidePair() {Hankaku = "[", Zenkaku = "［"},
            new NarrowWidePair() {Hankaku = "]", Zenkaku = "］"},
            new NarrowWidePair() {Hankaku = "{", Zenkaku = "｛"},
            new NarrowWidePair() {Hankaku = "}", Zenkaku = "｝"},
            new NarrowWidePair() {Hankaku = "ﾞ", Zenkaku = "゛"},
            new NarrowWidePair() {Hankaku = "ﾟ", Zenkaku = "゜"},
            new NarrowWidePair() {Hankaku = "､", Zenkaku = "、"},
            new NarrowWidePair() {Hankaku = "｡", Zenkaku = "。"},
            
//            new NarrowWidePair() {Hankaku = "\\", Zenkaku = "￥"},
//            new NarrowWidePair() {Hankaku = "\\", Zenkaku = "＼"},
        });

        public static readonly List<BigSmallPair> OOMOJI_KOMOJI_LIST = new List<BigSmallPair>(new[]
        {
            new BigSmallPair() {Small = "a", Big = "A"},
            new BigSmallPair() {Small = "b", Big = "B"},
            new BigSmallPair() {Small = "c", Big = "C"},
            new BigSmallPair() {Small = "d", Big = "D"},
            new BigSmallPair() {Small = "e", Big = "E"},
            new BigSmallPair() {Small = "f", Big = "F"},
            new BigSmallPair() {Small = "g", Big = "G"},
            new BigSmallPair() {Small = "h", Big = "H"},
            new BigSmallPair() {Small = "i", Big = "I"},
            new BigSmallPair() {Small = "j", Big = "J"},
            new BigSmallPair() {Small = "k", Big = "K"},
            new BigSmallPair() {Small = "l", Big = "L"},
            new BigSmallPair() {Small = "m", Big = "M"},
            new BigSmallPair() {Small = "n", Big = "N"},
            new BigSmallPair() {Small = "o", Big = "O"},
            new BigSmallPair() {Small = "p", Big = "P"},
            new BigSmallPair() {Small = "q", Big = "Q"},
            new BigSmallPair() {Small = "r", Big = "R"},
            new BigSmallPair() {Small = "s", Big = "S"},
            new BigSmallPair() {Small = "t", Big = "T"},
            new BigSmallPair() {Small = "u", Big = "U"},
            new BigSmallPair() {Small = "v", Big = "V"},
            new BigSmallPair() {Small = "w", Big = "W"},
            new BigSmallPair() {Small = "x", Big = "X"},
            new BigSmallPair() {Small = "y", Big = "Y"},
            new BigSmallPair() {Small = "z", Big = "Z"},
            new BigSmallPair() {Small = "ａ", Big = "Ａ"},
            new BigSmallPair() {Small = "ｂ", Big = "Ｂ"},
            new BigSmallPair() {Small = "ｃ", Big = "Ｃ"},
            new BigSmallPair() {Small = "ｄ", Big = "Ｄ"},
            new BigSmallPair() {Small = "ｅ", Big = "Ｅ"},
            new BigSmallPair() {Small = "ｆ", Big = "Ｆ"},
            new BigSmallPair() {Small = "ｇ", Big = "Ｇ"},
            new BigSmallPair() {Small = "ｈ", Big = "Ｈ"},
            new BigSmallPair() {Small = "ｉ", Big = "Ｉ"},
            new BigSmallPair() {Small = "ｊ", Big = "Ｊ"},
            new BigSmallPair() {Small = "ｋ", Big = "Ｋ"},
            new BigSmallPair() {Small = "ｌ", Big = "Ｌ"},
            new BigSmallPair() {Small = "ｍ", Big = "Ｍ"},
            new BigSmallPair() {Small = "ｎ", Big = "Ｎ"},
            new BigSmallPair() {Small = "ｏ", Big = "Ｏ"},
            new BigSmallPair() {Small = "ｐ", Big = "Ｐ"},
            new BigSmallPair() {Small = "ｑ", Big = "Ｑ"},
            new BigSmallPair() {Small = "ｒ", Big = "Ｒ"},
            new BigSmallPair() {Small = "ｓ", Big = "Ｓ"},
            new BigSmallPair() {Small = "ｔ", Big = "Ｔ"},
            new BigSmallPair() {Small = "ｕ", Big = "Ｕ"},
            new BigSmallPair() {Small = "ｖ", Big = "Ｖ"},
            new BigSmallPair() {Small = "ｗ", Big = "Ｗ"},
            new BigSmallPair() {Small = "ｘ", Big = "Ｘ"},
            new BigSmallPair() {Small = "ｙ", Big = "Ｙ"},
            new BigSmallPair() {Small = "ｚ", Big = "Ｚ"},
        });
    }
}